type Locale = 'ar' | 'en';

const pick = (locale: Locale, en: string, ar: string) => (locale === 'ar' ? ar : en);

export const adminCopy = {
  productTag: (locale: Locale) => pick(locale, 'PRO ADMIN', 'مسؤول PRO'),
  liveConnected: (locale: Locale) => pick(locale, 'Firestore connected', 'متصل بـ Firestore'),
  liveError: (locale: Locale) => pick(locale, 'Sync failed', 'فشلت المزامنة'),
  loading: (locale: Locale) => pick(locale, 'Loading', 'جارٍ التحميل'),
  ready: (locale: Locale) => pick(locale, 'Live', 'مباشر'),
  searchPlaceholder: (locale: Locale) => pick(locale, 'Search athletes, workouts, or UID…', 'ابحث عن رياضي أو تمرين أو معرف…'),
  searchLabel: (locale: Locale) => pick(locale, 'Search the platform', 'ابحث في المنصة'),
  clearSearch: (locale: Locale) => pick(locale, 'Clear search', 'مسح البحث'),
  toggleSidebar: (locale: Locale) => pick(locale, 'Toggle navigation', 'تبديل القائمة'),
  refresh: (locale: Locale) => pick(locale, 'Refresh data', 'تحديث البيانات'),
  exportCsv: (locale: Locale) => pick(locale, 'Export CSV', 'تصدير CSV'),
  switchToAthlete: (locale: Locale) => pick(locale, 'Switch to athlete view', 'التبديل إلى واجهة الرياضي'),
  signOut: (locale: Locale) => pick(locale, 'Sign out', 'تسجيل الخروج'),
  navAriaLabel: (locale: Locale) => pick(locale, 'Admin sections', 'أقسام لوحة التحكم'),
  sectionPulse: (locale: Locale) => pick(locale, 'Pulse & telemetry', 'التحليلات والمباشر'),
  sectionRoster: (locale: Locale) => pick(locale, 'Athletes & roster', 'الرياضيون والسجل'),
  sectionHealth: (locale: Locale) => pick(locale, 'Health & nutrition', 'الصحة والتغذية'),
  sectionSystem: (locale: Locale) => pick(locale, 'System & governance', 'النظام والحوكمة'),
  catOverview: (locale: Locale) => pick(locale, 'Executive pulse', 'نظرة عامة تنفيذية'),
  catRecords: (locale: Locale) => pick(locale, 'PRs & records', 'الأرقام القياسية'),
  catAthletes: (locale: Locale) => pick(locale, 'Athletes directory', 'دليل الرياضيين'),
  catWorkouts: (locale: Locale) => pick(locale, 'Workout logbook', 'سجل التمارين'),
  catNutrition: (locale: Locale) => pick(locale, 'Nutrition hub', 'مركز التغذية'),
  catGovernance: (locale: Locale) => pick(locale, 'System & security', 'النظام والأمان'),

  overviewEyebrow: (locale: Locale) => pick(locale, 'Executive telemetry pulse', 'لوحة القيادة التنفيذية'),
  overviewTitle: (locale: Locale) => pick(locale, 'Platform command center', 'مركز قيادة المنصة'),
  overviewSubtitle: (locale: Locale) =>
    pick(locale, 'Live roster activity, aggregate training volume, and energy expenditure.', 'نشاط الرياضيين، الحجم التدريبي الإجمالي، واستهلاك الطاقة.'),
  totalAthletes: (locale: Locale) => pick(locale, 'Total athletes', 'إجمالي الرياضيين'),
  activeRecently: (locale: Locale) => pick(locale, 'active in 30d', 'نشط خلال 30 يوم'),
  workoutsLogged: (locale: Locale) => pick(locale, 'Workouts logged', 'التمارين المسجلة'),
  plannedSessions: (locale: Locale) => pick(locale, 'planned in schedule', 'جلسة مجدولة'),
  volumeMoved: (locale: Locale) => pick(locale, 'Total volume moved', 'الحجم الإجمالي'),
  aggregateTonnage: (locale: Locale) => pick(locale, 'Aggregate set tonnage', 'مجموع تكرارات × الأوزان'),
  energyBurned: (locale: Locale) => pick(locale, 'Energy burned', 'السعرات المحروقة'),
  calorieExpenditure: (locale: Locale) => pick(locale, 'Calorie expenditure', 'حرق التمارين'),
  avgDuration: (locale: Locale) => pick(locale, 'Avg session', 'متوسط الجلسة'),
  standardLength: (locale: Locale) => pick(locale, 'Standard session length', 'مدة الجلسة القياسية'),
  nutritionEntries: (locale: Locale) => pick(locale, 'Nutrition entries', 'الوجبات المسجلة'),
  dietLogs: (locale: Locale) => pick(locale, 'Diet logs tracked', 'سجلات الماكروز'),
  liveStream: (locale: Locale) => pick(locale, 'Live workout stream', 'سجل الأنشطة الحية'),
  openLogbook: (locale: Locale) => pick(locale, 'Open logbook', 'فتح السجل'),
  noActivity: (locale: Locale) => pick(locale, 'No completed workouts yet. New sessions appear here instantly.', 'لا توجد تمارين مكتملة بعد. تظهر الجلسات الجديدة هنا فوراً.'),
  platformRecords: (locale: Locale) => pick(locale, 'Platform strength records', 'أبرز الأرقام القياسية'),
  allAthletes: (locale: Locale) => pick(locale, 'All athletes', 'جميع الرياضيين'),
  noPrs: (locale: Locale) => pick(locale, 'Records register automatically once weighted sets are logged.', 'تُسجل الأرقام تلقائياً بعد رفع الأوزان.'),
  discipline: (locale: Locale) => pick(locale, 'Discipline breakdown', 'توزيع التمارين حسب التخصص'),
  strength: (locale: Locale) => pick(locale, 'Strength', 'قوة'),
  hypertrophy: (locale: Locale) => pick(locale, 'Hypertrophy', 'تضخيم'),
  cardio: (locale: Locale) => pick(locale, 'Cardio', 'كارديو'),
  bodyweight: (locale: Locale) => pick(locale, 'Bodyweight', 'وزن الجسم'),
  exercisesCount: (locale: Locale, count: number) => pick(locale, `${count} exercises`, `${count} تمارين`),
  volumeShort: (locale: Locale, value: string) => pick(locale, `${value} kg vol`, `${value} كجم`),

  rosterEyebrow: (locale: Locale) => pick(locale, 'Athletes & roster intelligence', 'دليل الرياضيين المحترفين'),
  rosterTitle: (locale: Locale) => pick(locale, 'Athletes directory', 'سجل الرياضيين وإدارة الحسابات'),
  rosterSubtitle: (locale: Locale, shown: number, total: number) =>
    pick(locale, `Showing ${shown} of ${total} athletes. Select a row to open the full dossier.`, `عرض ${shown} من إجمالي ${total} رياضي. اختر صفاً لفتح الملف الكامل.`),
  filterAll: (locale: Locale) => pick(locale, 'All', 'الكل'),
  filterActive: (locale: Locale) => pick(locale, 'Active (30d)', 'النشطون (30 يوم)'),
  filterElite: (locale: Locale) => pick(locale, 'Elite & Pro', 'النخبة والمحترفون'),
  filterRookie: (locale: Locale) => pick(locale, 'Newcomers', 'المبتدئون'),
  sortBy: (locale: Locale) => pick(locale, 'Sort', 'ترتيب'),
  sortWorkouts: (locale: Locale) => pick(locale, 'Most workouts', 'الأكثر تماريناً'),
  sortTonnage: (locale: Locale) => pick(locale, 'Most volume', 'الأعلى حجماً'),
  sortCalories: (locale: Locale) => pick(locale, 'Most calories', 'الأعلى حرقاً'),
  sortRecent: (locale: Locale) => pick(locale, 'Recently active', 'الأحدث نشاطاً'),
  sortName: (locale: Locale) => pick(locale, 'Name A–Z', 'الاسم أبجدياً'),
  colAthlete: (locale: Locale) => pick(locale, 'Athlete', 'الرياضي'),
  colTier: (locale: Locale) => pick(locale, 'Tier', 'المستوى'),
  colWorkouts: (locale: Locale) => pick(locale, 'Workouts', 'التمارين'),
  colTonnage: (locale: Locale) => pick(locale, 'Volume', 'الحجم'),
  colCalories: (locale: Locale) => pick(locale, 'Calories', 'السعرات'),
  colLastActive: (locale: Locale) => pick(locale, 'Last active', 'آخر نشاط'),
  colActions: (locale: Locale) => pick(locale, 'Actions', 'الإجراء'),
  openDossier: (locale: Locale) => pick(locale, 'Open dossier', 'فتح الملف'),
  never: (locale: Locale) => pick(locale, 'Never', 'لم يسجل'),
  daysAgo: (locale: Locale, days: number) => pick(locale, `${days}d ago`, `منذ ${days} يوم`),
  today: (locale: Locale) => pick(locale, 'Today', 'اليوم'),
  emptyRosterTitle: (locale: Locale) => pick(locale, 'No athletes match this view', 'لا يوجد رياضيون يطابقون هذا العرض'),
  emptyRosterBody: (locale: Locale) => pick(locale, 'Adjust the search term or pick a different filter.', 'غيّر كلمة البحث أو اختر فلتراً آخر.'),
  pageSize: (locale: Locale) => pick(locale, 'Rows', 'صفوف'),
  page: (locale: Locale, current: number, total: number) => pick(locale, `Page ${current} of ${total}`, `صفحة ${current} من ${total}`),
  prevPage: (locale: Locale) => pick(locale, 'Previous page', 'الصفحة السابقة'),
  nextPage: (locale: Locale) => pick(locale, 'Next page', 'الصفحة التالية'),
  resultsCount: (locale: Locale, shown: number, total: number) => pick(locale, `${shown} of ${total} athletes`, `${shown} من ${total} رياضي`),

  drawerTitle: (locale: Locale) => pick(locale, 'Athlete dossier', 'ملف الرياضي'),
  drawerClose: (locale: Locale) => pick(locale, 'Close dossier', 'إغلاق الملف'),
  tabWorkouts: (locale: Locale) => pick(locale, 'Workouts', 'التمارين'),
  tabRecords: (locale: Locale) => pick(locale, 'Records', 'الأرقام'),
  tabPlanned: (locale: Locale) => pick(locale, 'Planned', 'المجدولة'),
  tabMeals: (locale: Locale) => pick(locale, 'Meals', 'الوجبات'),
  tabWeight: (locale: Locale) => pick(locale, 'Weight', 'الوزن'),
  uidLabel: (locale: Locale) => pick(locale, 'User ID', 'معرف المستخدم'),
  setLabel: (locale: Locale) => pick(locale, 'Set', 'جولة'),
  repsLabel: (locale: Locale) => pick(locale, 'reps', 'تكرار'),
  expandWorkout: (locale: Locale) => pick(locale, 'Expand workout details', 'عرض تفاصيل التمرين'),
  collapseWorkout: (locale: Locale) => pick(locale, 'Collapse workout details', 'إخفاء تفاصيل التمرين'),
  emptyTab: (locale: Locale) => pick(locale, 'Nothing recorded here yet.', 'لا توجد سجلات هنا بعد.'),
  bodyFat: (locale: Locale) => pick(locale, 'Body fat', 'نسبة الدهون'),

  workoutsEyebrow: (locale: Locale) => pick(locale, 'Training intelligence', 'سجل التدريب الذكي'),
  workoutsTitle: (locale: Locale) => pick(locale, 'Global workout logbook', 'سجل التمارين المكتملة'),
  workoutsSubtitle: (locale: Locale, count: number) =>
    pick(locale, `${count} completed sessions across every athlete, newest first.`, `${count} جلسة مكتملة عبر جميع الرياضيين، الأحدث أولاً.`),
  emptyWorkoutsTitle: (locale: Locale) => pick(locale, 'No workouts in this discipline', 'لا توجد تمارين في هذا التصنيف'),
  emptyWorkoutsBody: (locale: Locale) => pick(locale, 'Choose a different training filter to see more.', 'اختر تصنيفاً آخر لمشاهدة المزيد.'),
  sessionFallback: (locale: Locale) => pick(locale, 'Workout session', 'جلسة تمرين'),

  nutritionEyebrow: (locale: Locale) => pick(locale, 'Nutrition & metabolic telemetry', 'إحصائيات التغذية والسعرات'),
  nutritionTitle: (locale: Locale) => pick(locale, 'Nutrition intelligence hub', 'مركز التغذية وتوزيع الماكروز'),
  nutritionSubtitle: (locale: Locale, count: number) =>
    pick(locale, `Tracking ${count} logged meals with full macronutrient breakdowns.`, `متابعة ${count} وجبة مسجلة مع توزيع الماكروز.`),
  totalProtein: (locale: Locale) => pick(locale, 'Total protein', 'إجمالي البروتين'),
  totalCarbs: (locale: Locale) => pick(locale, 'Total carbs', 'إجمالي الكربوهيدرات'),
  totalFats: (locale: Locale) => pick(locale, 'Total fats', 'إجمالي الدهون'),
  emptyMealsTitle: (locale: Locale) => pick(locale, 'No logged meals yet', 'لا توجد وجبات مسجلة بعد'),
  emptyMealsBody: (locale: Locale) => pick(locale, 'Meals logged by athletes appear here instantly.', 'تظهر وجبات الرياضيين هنا فور تسجيلها.'),

  recordsEyebrow: (locale: Locale) => pick(locale, 'Strength benchmarks', 'سجلات القوة'),
  recordsTitle: (locale: Locale) => pick(locale, 'Platform PR leaderboard', 'لوحة الأرقام القياسية'),
  recordsSubtitle: (locale: Locale) =>
    pick(locale, 'Heaviest recorded lift per exercise across every athlete.', 'أثقل وزن مسجل لكل تمرين عبر جميع الرياضيين.'),
  emptyRecordsTitle: (locale: Locale) => pick(locale, 'No personal records yet', 'لا توجد أرقام قياسية بعد'),
  emptyRecordsBody: (locale: Locale) => pick(locale, 'Records register as soon as weighted sets are logged.', 'تُسجل الأرقام فور رفع الأوزان.'),
  colRank: (locale: Locale) => pick(locale, 'Rank', 'المركز'),
  colExercise: (locale: Locale) => pick(locale, 'Exercise', 'التمرين'),
  colHeaviest: (locale: Locale) => pick(locale, 'Heaviest lift', 'أثقل رفع'),
  colHolder: (locale: Locale) => pick(locale, 'Record holder', 'حامل الرقم'),
  colDate: (locale: Locale) => pick(locale, 'Achieved', 'تاريخ الإنجاز'),

  governanceEyebrow: (locale: Locale) => pick(locale, 'Governance & integrity', 'الحوكمة وسلامة البيانات'),
  governanceTitle: (locale: Locale) => pick(locale, 'Master system controls', 'إعدادات النظام الرئيسية'),
  governanceSubtitle: (locale: Locale) =>
    pick(locale, 'Cloud connection status, security posture, and master backup utilities.', 'حالة الاتصال السحابي، وضع الأمان، وأدوات النسخ الاحتياطي.'),
  adminAccount: (locale: Locale) => pick(locale, 'Master administrator', 'حساب المشرف الرئيسي'),
  adminEmailLabel: (locale: Locale) => pick(locale, 'Authorized admin email', 'البريد الإلكتروني المعتمد'),
  securityLevel: (locale: Locale) => pick(locale, 'Security level', 'مستوى الصلاحيات'),
  securityLevelValue: (locale: Locale) => pick(locale, 'Full read access to athlete collections', 'تحكم كامل بقراءة سجلات الرياضيين'),
  passwordProtected: (locale: Locale) => pick(locale, 'Password protected', 'محمي بكلمة مرور'),
  dbTelemetry: (locale: Locale) => pick(locale, 'Database telemetry', 'حالة قاعدة البيانات'),
  storageEngine: (locale: Locale) => pick(locale, 'Storage engine', 'محرك التخزين'),
  storageEngineValue: (locale: Locale) => pick(locale, 'Firestore multi-tab persistent cache', 'ذاكرة Firestore الدائمة'),
  securityRules: (locale: Locale) => pick(locale, 'Security rules', 'قواعد الأمان'),
  securityRulesValue: (locale: Locale) => pick(locale, 'Enforced by role claim verification', 'مُفعّلة عبر التحقق من صلاحية الحساب'),
  masterBackup: (locale: Locale) => pick(locale, 'Platform master backup', 'النسخ الاحتياطي الشامل'),
  backupBody: (locale: Locale) =>
    pick(locale, 'Download every athlete, workout, and meal record in one JSON snapshot.', 'تنزيل جميع بيانات الرياضيين والتمارين والوجبات في ملف JSON واحد.'),
  downloadBackup: (locale: Locale) => pick(locale, 'Download backup', 'تنزيل النسخة'),
  resync: (locale: Locale) => pick(locale, 'Re-sync', 'إعادة المزامنة'),
  statusOk: (locale: Locale) => pick(locale, 'Active', 'نشط'),
  statusEnforced: (locale: Locale) => pick(locale, 'Enforced', 'مُفعّل'),
  statusVerified: (locale: Locale) => pick(locale, 'Verified', 'موثّق'),

  errorTitle: (locale: Locale) => pick(locale, 'We could not load the platform data', 'تعذر تحميل بيانات المنصة'),
  errorBody: (locale: Locale) =>
    pick(locale, 'The Firestore request failed or timed out. Nothing was changed — retry when you are ready.', 'فشل الطلب أو انتهت مهلته. لم يتغيّر شيء، أعد المحاولة.'),
  retry: (locale: Locale) => pick(locale, 'Try again', 'إعادة المحاولة'),
  loadingTitle: (locale: Locale) => pick(locale, 'Synchronising live telemetry', 'جاري مزامنة البيانات المباشرة'),
  loadingBody: (locale: Locale) => pick(locale, 'Reading athlete collections from Firestore.', 'قراءة سجلات الرياضيين من Firestore.'),
  skeletonRows: (locale: Locale) => pick(locale, 'Loading rows', 'جارٍ تحميل الصفوف'),
  syncedToast: (locale: Locale) => pick(locale, 'Live telemetry synced ⚡', 'تمت مزامنة البيانات ⚡'),
  failedToast: (locale: Locale) => pick(locale, 'Failed to synchronise live data.', 'تعذرت مزامنة البيانات.'),
  exportToast: (locale: Locale) => pick(locale, 'Roster exported to CSV', 'تم تصدير الرياضيين إلى CSV'),
  backupToast: (locale: Locale) => pick(locale, 'System backup downloaded', 'تم تنزيل النسخة الاحتياطية')
};
